version: '3.4'

services:
  serverdatn:
    image: serverdatn
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - ./.env:/app/.env 
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
