version: '3.4'

services:
  serverdatn:
    container_name: serverdatn
    image: serverdatn
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - '27012:27017'
  
